title:             J's log
email:             mirinae312@gmail.com
description:       J's log
author:            juno
baseurl:           ""
url:               "https://mirinae312.github.io"

# Social Profiles
github_username:   mirinae312
linkedin_username: mirinae312

# Build settings
markdown:          kramdown
#paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

highlighter:      rouge


collections:
  category_index:
    permalink:       /category/:name/
    output:          true

#pagination:
#  enabled: true
#  per_page: 10
#  limit: 0
#  sort_field: "date"
#  sort_reverse: true